### ISSUE TITLE
Diseño de plantilla para pruebas

### ISSUE THREAD

**Issue by MarlinDayana** [MarlinDayana/MisionTic2022DreamTeam#9]
El **tester** diseñará un modelo/plantilla donde se pueda tener la trazabilidad de las actividades (de pruebas) durante el tiempo.

**Comment by jorgeramirezj** [comment]
Anexo de ruta donde se aloja el documento de pruebas
https://drive.google.com/drive/folders/1YSN9eBonVrHllGPw6MCGi0DtZQHiYulN?usp=sharing
